### ISSUE TITLE
An issue about the other project —order-matters 

### ISSUE THREAD

**Issue by whetherstu** [GYolanda/SmartHomePro#1]
Excuse me,I would like to consult about the specific problems solved by the different files in your previous project, as well as the dependencies and operation of the file execution

**Comment by meng-wenlong** [comment]
I apologize for withdrawing the Order-Matters repository without a statement. It was a work I did when I was a co-author of a measurement paper, which is still under review. I've left that work and gave the code to the first author to maintain. Order-Matters' input requires a specific format, which is generated by other works of the paper. I'm sorry I may not be able to help you.

**Comment by whetherstu** [comment]
Thank you very much, I am a graduate student at Beijing University of Posts and Telecommunications, and I have recently been doing a reproduction of the article of OrderMatters for comparative experiments, if other people on your team have relevant work you can tell me, I will try to consult them further.I   apologize for any interruptions.

**Comment by meng-wenlong** [comment]
Good luck with your experiment! The first author said she would open-source all code after the paper being accepted. I'll contact you if the paper is accepted.
I'll close this issue for now. Feel free to reopen if there's further question!
